Implement task updates from Github webhook
City-of-Helsinki/helpt pull request #5
Opened 2016-10-14 15:15 UTC by vikoivun

2016-10-18 07:16 UTC, juyrjola requested changes

2016-10-18 07:16 UTC, juyrjola commented on helpt/urls.py
> +from projects.adapters.github_hook import urls as github_urls
I think `github.py` has not grown to be too big to include the hook code, as well. So move the contents of `github_hook.py` into `github.py`.

2016-10-18 07:16 UTC, juyrjola commented on helpt/urls.py
> +    url(r'^hooks/github', include(github_urls, namespace='github_hook')),
Should this have a trailing slash? Also, `namespace` is unnecessary here. If you want to name your view, name it in `github_urls`.

2016-10-18 11:42 UTC, vikoivun commented on helpt/urls.py
> +from projects.adapters.github_hook import urls as github_urls
That causes a circular import of Workspace -> GitHubAdater -> Workspace, thus necessitating the usage of:
`import django
Workspace = django.apps.apps.get_model('projects', 'Workspace')`

I had that first, but it seemed _unclean_ somehow. Is that still the way it should be done?

2016-10-18 14:56 UTC, vikoivun commented on helpt/urls.py
> +    url(r'^hooks/github', include(github_urls, namespace='github_hook')),
Yea, it probably should. Will remove namespace too.

2016-10-19 06:23 UTC, juyrjola commented on helpt/urls.py
> +from projects.adapters.github_hook import urls as github_urls
Hmm, maybe some kind of adapter registry would work better here. Let's go with your original solution for now.

2016-10-25 12:39 UTC, closed without merging